In [1]:
import os
import torch
import pandas as pd
from torchvision import transforms
from torchvision.transforms import Normalize, ToTensor
from PIL import Image
from brisque import BRISQUE
from tqdm import tqdm

In [2]:
def parse_dirs(input_dir: str) -> pd.DataFrame:
    items = []
    for dirname, _, filenames in os.walk(input_dir):
        for filename in filenames:
            items.append(
                [
                    os.path.join(dirname, filename),
                    dirname[dirname.rfind("/") + 1:].capitalize(),
                ]
            )
    return pd.DataFrame(items, columns=["image", "label"])

def pil_loader(path):
    with open(path, 'rb') as f:
        img = Image.open(f)
        return img.convert('RGB')

In [3]:
ds = parse_dirs("/mnt/c/Datasets/DermNet/train/")
ds

,image,label
0,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
1,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
2,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
3,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
4,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
...,...,...
15552,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections
15553,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections
15554,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections
15555,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections
15556,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections

In [13]:
obj = BRISQUE(url=False)


ds = pd.read_csv("/home/ilya/documents/HESH/ML/notebooks/images.csv")
scores = [0] * ds.shape[0]
img_iter = tqdm(range(ds.shape[0]))
for j in img_iter:
    if j == 1000:
        break
    img = pil_loader(ds["image"][j])
    score = obj.score(img)
    scores[j] = score
    img_iter.set_description(f"Image: {j}, score: {score}")
        
ds["brisque_scores"] = scores
ds.to_csv("/home/ilya/documents/HESH/ML/data/processed/images_b.csv")

Image: 999, score: 27.73423504578406:   6%|▋         | 1000/15557 [04:30<1:05:35,  3.70it/s]

In [6]:
ds_m = pd.read_csv("/home/ilya/documents/HESH/ML/data/processed/images.csv")[:1000]
ds_h = pd.read_csv("/home/ilya/documents/HESH/ML/data/processed/images_h.csv")[:1000]
ds_b = pd.read_csv("/home/ilya/documents/HESH/ML/data/processed/images_b.csv")[:1000]

In [9]:
ds_m.describe()

       Unnamed: 0.1   Unnamed: 0  maniqa_scores
count   1000.000000  1000.000000    1000.000000
mean     499.500000   499.500000       0.513911
std      288.819436   288.819436       0.047099
min        0.000000     0.000000       0.307851
25%      249.750000   249.750000       0.488137
50%      499.500000   499.500000       0.518514
75%      749.250000   749.250000       0.544405
max      999.000000   999.000000       0.662624

In [23]:
ds_m[ds_m["maniqa_scores"] > 0.6]

,Unnamed: 0.1,Unnamed: 0,image,label,maniqa_scores
145,145,145,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.610687
231,231,231,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.608504
235,235,235,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.616707
368,368,368,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.623429
509,509,509,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.623954
510,510,510,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.612797
511,511,511,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.634814
531,531,531,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.662624
537,537,537,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.607798
589,589,589,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.602730
636,636,636,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.603145
707,707,707,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.600114
733,733,733,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.614106
842,842,842,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.600927
896,896,896,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.619961
902,902,902,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.605778
925,925,925,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.600237
930,930,930,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.603524

In [ ]:
Image.open(ds_m.iloc[368].image)

In [27]:
ds_h.describe()

       Unnamed: 0.1   Unnamed: 0  hyperiqa_scores
count   1000.000000  1000.000000      1000.000000
mean     499.500000   499.500000        64.954521
std      288.819436   288.819436         4.789880
min        0.000000     0.000000        45.031621
25%      249.750000   249.750000        62.767839
50%      499.500000   499.500000        65.647504
75%      749.250000   749.250000        68.138682
max      999.000000   999.000000        76.369308

In [60]:
ds_h[ds_h["hyperiqa_scores"] > 73]

,Unnamed: 0.1,Unnamed: 0,image,label,hyperiqa_scores
28,28,28,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,73.217320
107,107,107,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,76.369308
195,195,195,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,74.110685
235,235,235,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,74.184230
547,547,547,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,74.161227
551,551,551,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,74.591536
589,589,589,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,73.941922
670,670,670,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,74.710613
671,671,671,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,73.136196
689,689,689,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,74.385746
690,690,690,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,74.679724
691,691,691,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,73.151650
704,704,704,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,74.963467
741,741,741,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,73.380578
940,940,940,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,74.617847

In [ ]:
Image.open(ds_h.iloc[107].image)

In [43]:
ds_b.describe()

       Unnamed: 0.1   Unnamed: 0  brisque_scores
count   1000.000000  1000.000000     1000.000000
mean     499.500000   499.500000       17.541821
std      288.819436   288.819436       10.359170
min        0.000000     0.000000       -4.741551
25%      249.750000   249.750000       10.596064
50%      499.500000   499.500000       16.081267
75%      749.250000   749.250000       22.201129
max      999.000000   999.000000       79.657409

In [50]:
ds_b[ds_b["brisque_scores"] > 60]

,Unnamed: 0.1,Unnamed: 0,image,label,brisque_scores
74,74,74,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,71.343920
92,92,92,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,79.657409
374,374,374,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,61.911718

In [ ]:
Image.open(ds_b.iloc[374].image)