In [1]:
import os
import torch
import pandas as pd
from torchvision import transforms
from torchvision.transforms import Normalize, ToTensor
from PIL import Image
from brisque import BRISQUE
from tqdm import tqdm

In [80]:
def parse_dirs(input_dir: str) -> pd.DataFrame:
    items = []
    for dirname, _, filenames in os.walk(input_dir):
        for filename in filenames:
            items.append(
                [
                    os.path.join(dirname, filename),
                    dirname[dirname.rfind("/") + 1:].capitalize(),
                ]
            )
    return pd.DataFrame(items, columns=["image", "label"])

def pil_loader(path):
    with open(path, 'rb') as f:
        img = Image.open(f)
        return img.convert('RGB')

In [81]:
ds = parse_dirs("/mnt/c/Datasets/DermNet/train/")
ds

,image,label
0,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
1,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
2,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
3,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
4,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos
...,...,...
15552,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections
15553,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections
15554,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections
15555,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections
15556,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections

In [13]:
obj = BRISQUE(url=False)


ds = pd.read_csv("/home/ilya/documents/HESH/ML/notebooks/images.csv")
scores = [0] * ds.shape[0]
img_iter = tqdm(range(ds.shape[0]))
for j in img_iter:
    if j == 1000:
        break
    img = pil_loader(ds["image"][j])
    score = obj.score(img)
    scores[j] = score
    img_iter.set_description(f"Image: {j}, score: {score}")
        
ds["brisque_scores"] = scores
ds.to_csv("/home/ilya/documents/HESH/ML/data/processed/images_b.csv")

Image: 999, score: 27.73423504578406:   6%|▋         | 1000/15557 [04:30<1:05:35,  3.70it/s]

In [2]:
ds_m = pd.read_csv("/home/ilya/documents/HESH/ML/data/processed/images.csv")[:1000]
ds_h = pd.read_csv("/home/ilya/documents/HESH/ML/data/processed/images_h.csv")[:1000]
ds_b = pd.read_csv("/home/ilya/documents/HESH/ML/data/processed/images_b.csv")[:1000]

In [9]:
ds_m.describe()

       Unnamed: 0.1   Unnamed: 0  maniqa_scores
count   1000.000000  1000.000000    1000.000000
mean     499.500000   499.500000       0.513911
std      288.819436   288.819436       0.047099
min        0.000000     0.000000       0.307851
25%      249.750000   249.750000       0.488137
50%      499.500000   499.500000       0.518514
75%      749.250000   749.250000       0.544405
max      999.000000   999.000000       0.662624

In [23]:
ds_m[ds_m["maniqa_scores"] > 0.6]

,Unnamed: 0.1,Unnamed: 0,image,label,maniqa_scores
145,145,145,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.610687
231,231,231,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.608504
235,235,235,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.616707
368,368,368,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.623429
509,509,509,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.623954
510,510,510,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.612797
511,511,511,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.634814
531,531,531,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.662624
537,537,537,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.607798
589,589,589,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.602730
636,636,636,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.603145
707,707,707,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.600114
733,733,733,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,0.614106
842,842,842,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.600927
896,896,896,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.619961
902,902,902,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.605778
925,925,925,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.600237
930,930,930,/mnt/c/Datasets/DermNet/train/Actinic Keratosi...,Actinic keratosis basal cell carcinoma and oth...,0.603524

In [ ]:
Image.open(ds_m.iloc[368].image)

In [13]:
ds_h.describe()

       Unnamed: 0.1   Unnamed: 0  hyperiqa_scores
count   1000.000000  1000.000000      1000.000000
mean     499.500000   499.500000        64.954521
std      288.819436   288.819436         4.789880
min        0.000000     0.000000        45.031621
25%      249.750000   249.750000        62.767839
50%      499.500000   499.500000        65.647504
75%      749.250000   749.250000        68.138682
max      999.000000   999.000000        76.369308

In [16]:
ds_h[ds_h["hyperiqa_scores"] < 50]

,Unnamed: 0.1,Unnamed: 0,image,label,hyperiqa_scores
55,55,55,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,45.031621
67,67,67,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,45.527267
82,82,82,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,48.187014
181,181,181,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,45.405868
183,183,183,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,48.982185
420,420,420,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,49.511917
490,490,490,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,49.974760
500,500,500,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,48.717178
523,523,523,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,47.813140
539,539,539,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,49.639590
540,540,540,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,47.995779
789,789,789,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,47.248356
790,790,790,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,48.218402

In [ ]:
Image.open(ds_h.iloc[539].image)

In [3]:
ds_b.describe()

       Unnamed: 0.1   Unnamed: 0  brisque_scores
count   1000.000000  1000.000000     1000.000000
mean     499.500000   499.500000       17.541821
std      288.819436   288.819436       10.359170
min        0.000000     0.000000       -4.741551
25%      249.750000   249.750000       10.596064
50%      499.500000   499.500000       16.081267
75%      749.250000   749.250000       22.201129
max      999.000000   999.000000       79.657409

In [11]:
ds_b[ds_b["brisque_scores"] > 60]

,Unnamed: 0.1,Unnamed: 0,image,label,brisque_scores
74,74,74,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,71.343920
92,92,92,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,79.657409
374,374,374,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,61.911718

In [ ]:
Image.open(ds_b.iloc[374].image)

In [87]:
import numpy as np
from src.entities.predict_params import PredictPipelineParams
from src.models.iqa_models import HyperNet, TargetNet


model_hyper = HyperNet(16, 112, 224, 112, 56, 28, 14, 7).cuda()
model_hyper.train(False)
model_hyper.load_state_dict((torch.load("/home/ilya/documents/HESH/ML/models/koniq_pretrained.pkl")))

transformer = transforms.Compose(
    [
        transforms.Resize((512, 384)),
        transforms.RandomCrop(size=224),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)
        ),
    ]
)

def predict(img):
    # random crop 10 patches and calculate mean quality score
    # quality score ranges from 0-100, a higher score indicates a better quality

    pred_scores = []
    for _ in range(10):
        img_tensor = transformer(img)
        img_tensor = torch.tensor(img_tensor.cuda()).unsqueeze(0)
        weights = model_hyper(img_tensor)

        model_target = TargetNet(weights).cuda()
        for param in model_target.parameters():
            param.requires_grad = False

        pred = model_target(weights["target_in_vec"])
        pred_scores.append(float(pred.item()))
    score = np.mean(sorted(pred_scores)[-3:])
    return score

config = PredictPipelineParams(
    model_path="models/koniq_pretrained.pkl",
    image_path="/mnt/c/Datasets/DermNet/train/Acne and Rosacea Photos/07Acne081101.jpg",
    num_parts=10,
)

# img = Image.open(config.image_path).convert("RGB")
# predict(img)

In [88]:
scores = [0] * ds.shape[0]
img_iter = tqdm(range(ds.shape[0]))
try:
    for j in img_iter:
        img = Image.open(ds["image"][j]).convert("RGB")
        score = predict(img)
        scores[j] = score
        img_iter.set_description(f"Image: {j}, score: {score}")

except KeyboardInterrupt:
    print("Stop")
finally:
    ds["scores"] = scores
    ds.to_csv("")

  0%|          | 0/15557 [00:00<?, ?it/s]/tmp/ipykernel_291/2134633695.py:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  img_tensor = torch.tensor(img_tensor.cuda()).unsqueeze(0)
Image: 15556, score: 65.19431559244792: 100%|██████████| 15557/15557 [41:33<00:00,  6.24it/s]

In [92]:
ds_h = pd.read_csv("/home/ilya/documents/HESH/ML/data/processed/images_h2.csv")
ds_h.describe()

         Unnamed: 0        scores
count  15557.000000  15557.000000
mean    7778.000000     66.444125
std     4491.063404      4.943685
min        0.000000     35.215101
25%     3889.000000     63.877534
50%     7778.000000     67.000829
75%    11667.000000     69.722377
max    15556.000000     80.486491

In [107]:
ds_h[ds_h["scores"] < 60]

,Unnamed: 0,image,label,scores
50,50,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,57.117720
53,53,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,57.256015
55,55,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,46.861767
67,67,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,47.522575
82,82,/mnt/c/Datasets/DermNet/train/Acne and Rosacea...,Acne and rosacea photos,53.309952
...,...,...,...,...
15504,15504,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections,53.407800
15520,15520,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections,53.941669
15526,15526,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections,56.076041
15533,15533,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections,57.180658
15547,15547,/mnt/c/Datasets/DermNet/train/Warts Molluscum ...,Warts molluscum and other viral infections,58.528023

In [ ]:
Image.open(ds.image[15504])